BotConstructor/Models/Bot/BotEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BotConstructor.Web.Models.Bot
{
    public class BotEditViewModel
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public string Name { get; set; }
        public List<BotMessage> Messages { get; set; }

        public BotEditViewModel()
        {
            Messages = new List<BotMessage>(); 
        }
        
    }

    public class BotMessage
    {
        public int Id { get; set; }
        public string InputMessage { get; set; }
        public string OutputMessage { get; set; }
    }
}

BotConstructor/Models/Bot/BotListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BotConstructor.Web.Models.Bot
{
    public class BotListViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsWorking { get; set; }
    }
}

BotConstructor/Models/Bot/BotViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BotConstructor.Web.Models.Bot
{
    public class BotViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Token { get; set; }
        public string Name { get; set; }
    }
}

BotConstructor/Models/Bot/DashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BotConstructor.Web.Models.Bot
{
    public class DashboardViewModel
    {
        public int BotId { get; set; }
        public string BotName { get; set; }
    }
}

BotConstructor/Controllers/BotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BotConstructor.Bot;
using BotConstructor.Database.Models;
using BotConstructor.Web.Models.Bot;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BotConstructor.Web.Controllers
{  

    public class BotController : Controller
    {
        private ApplicationContext _context;
        public BotController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> List()
        {
            var model = await _context.Bots.Select(x => new BotListViewModel()
            {
                Id = x.Id, 
                Name = x.Title, 
                IsWorking = x.isWorking
            }).ToListAsync(); 
            return View(model);
        }

        public async Task<IActionResult> Dashboard(int id)
        {
            if(id > 0)
            {
                var bot = await _context.Bots.FirstOrDefaultAsync(x => x.Id == id);
                if(bot != null) return View(new DashboardViewModel { BotId = bot.Id, BotName = bot.Title });
            }

            return RedirectToAction("List"); 
        }

        public async Task<IActionResult> Edit(int id)
        {
            if(id > 0)
            {
                var bot = await _context.Bots.Include(x => x.Messages).FirstOrDefaultAsync(x => x.Id == id);
                if (bot != null)
                {
                    var model = new BotEditViewModel
                    {
                        Id = bot.Id,
                        Token = bot.Token,
                        Name = bot.Title,
                        Messages = bot.Messages.Select(x => new BotMessage
                        {
                            Id = x.Id,
                            InputMessage = x.InputMessage,
                            OutputMessage = x.OutputMessage
                        }).ToList() 
                    };
                    return View(model);
                }
            }

            return RedirectToAction("List"); 
        }


        [HttpPost]
        public async Task<IActionResult> AddBot(BotViewModel model)
        {
            BotControl control = new BotControl();
            await _context.Bots.AddAsync(new Database.Models.Bot { 
                BotId = control.StartBot(model.Token), 
                isWorking = true,
                Title = model.Name, 
                Token = model.Token
            });
            await _context.SaveChangesAsync(); 
            return RedirectToAction("List"); 
        }

        public async Task<IActionResult> StartBot(int id)
        {
            if(id > 0)
            {
                
                var bot = await _context.Bots.FirstOrDefaultAsync(x => x.Id == id); 
                if(bot != null && !bot.isWorking)
                {
                    BotControl control = new BotControl();
                    control.StartBot(bot.Token);

                    bot.isWorking = true;
                    _context.Bots.Update(bot);
                    await _context.SaveChangesAsync(); 
                }
            }

            return RedirectToAction("List");
        }

        //public async Task<IActionResult> StopBot(int id)
        //{
        //    if(id > 0)
        //    {
        //        var bot = await _context.Bots.FirstOrDefaultAsync(x => x.Id == id);
        //        if (bot != null && bot.isWorking)
        //        {
        //            BotControl control = new BotControl();
        //            control.StopBot(bot.Token);

        //            bot.isWorking = true;
        //            _context.Bots.Update(bot);
        //            await _context.SaveChangesAsync();
        //        }
        //    }
        //}
    }
}

BotConstructor/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BotConstructor.Database.Models;
using BotConstructor.Web.Models.Message;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BotConstructor.Web.Controllers
{
    public class MessageController : Controller
    {
        private ApplicationContext _context; 

        public MessageController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> List(int botId)
        {
            if (botId > 0)
            {
                var messageList = await _context.Messages.Where(x => x.BotId == botId).ToListAsync();
                var model = new MessageListViewModel
                {
                    BotId = botId,
                    Messages = messageList
                }; 

                return View(model);
            }
            return Redirect(Url.Action("List", "Bot"));
        }

        public IActionResult Create(int botId)
        {
            if (botId > 0)
            {
                var model = new MessageViewModel { BotId = botId };
                return View(model); 
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Create(MessageViewModel model)
        {
            if(ModelState.IsValid)
            {
                await _context.Messages.AddAsync(new Message
                {
                    InputMessage = model.InputMessage,
                    OutputMessage = model.OutputMessage,
                    BotId = model.BotId
                });

                await _context.SaveChangesAsync();

                return RedirectToAction("List", new { botId = model.BotId });
            }

            return View(model);
        }

        public async Task<IActionResult> Edit(int id)
        {       
            if(id > 0)
            {
                var msg = await _context.Messages.FirstOrDefaultAsync(x => x.Id == id);
                if(msg != null)
                {
                    var model = new MessageViewModel
                    {
                        Id = msg.Id,
                        InputMessage = msg.InputMessage,
                        OutputMessage = msg.OutputMessage,
                        BotId = msg.BotId
                    };
                    return View(model);
                }  
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MessageViewModel model)
        {
            if (ModelState.IsValid)
            {
                var msg = await _context.Messages.FirstAsync(x => x.Id == model.Id);

                if(msg != null)
                {
                    msg.InputMessage = model.InputMessage;
                    msg.OutputMessage = model.OutputMessage;
                    msg.BotId = model.BotId;

                    await _context.SaveChangesAsync();
                }               

                return RedirectToAction("List", new { botId = model.BotId});
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var message = await _context.Messages.FirstOrDefaultAsync(x => x.Id == id);

            if (message != null)
            {
                _context.Messages.Remove(message);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("List", new { botId = message.BotId }); 
        }
    }
}

BotConstructor/Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BotConstructor.Database.Models;
using BotConstructor.Database.Models.QuizModels;
using BotConstructor.Web.Models.Quiz;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BotConstructor.Web.Controllers
{
    public class QuizController : Controller
    {
        private ApplicationContext _context;
        public QuizController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> List(int botId)
        {
            if(botId > 0)
            {
                var quizzes = await _context.Quizzes.Where(x => x.BotId == botId).ToListAsync();
                var model = new QuizListViewModel
                {
                    BotId = botId,
                    Quizzes = quizzes
                };

                return View(model); 
            }
            return Redirect(Url.Action("List", "Bot")); 
        }

        public IActionResult Create(int botId)
        {
            if (botId > 0) return View(new QuizEditViewModel { BotId = botId }); 
            return RedirectToAction("List"); 
        }

        [HttpPost]
        public async Task<IActionResult> Create(QuizEditViewModel model)
        {
            if(ModelState.IsValid)
            {
                await _context.Quizzes.AddAsync(new Quiz
                {
                    BotId = model.BotId, 
                    Name = model.Name, 
                    TriggerCommand = model.TriggerCommand
                });
                await _context.SaveChangesAsync();
                return RedirectToAction("List", new { botId = model.BotId }); 
            }

            return View(model); 
        }

        public async Task<IActionResult> Edit(int id)
        {
            if(id > 0)
            {
                var quiz = await _context.Quizzes.Include(x => x.QuizSteps).FirstOrDefaultAsync(x => x.Id == id); 
                if(quiz != null)
                {
                    var model = new QuizEditViewModel
                    {
                        Id = quiz.Id,
                        BotId = quiz.BotId,
                        Name = quiz.Name,
                        TriggerCommand = quiz.TriggerCommand,
                        Steps = quiz.QuizSteps.Select(x => new QuizStepViewModel
                        {
                            Id = x.Id, 
                            QuizId = x.QuizId, 
                            Name = x.Name, 
                            Text = x.Text
                        }).ToList()
                    };

                    return View(model); 
                }
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(QuizEditViewModel model)
        {
            if(ModelState.IsValid)
            {
                var quiz = await _context.Quizzes.FirstOrDefaultAsync(x => x.Id == model.Id); 
                if(quiz != null)
                {
                    quiz.Name = model.Name;
                    quiz.TriggerCommand = model.TriggerCommand;
                }

                await _context.SaveChangesAsync();
                return RedirectToAction("List", new { botId = model.BotId }); 
            }

            return View(model); 
        }

        public async Task<IActionResult> Delete(int id)
        {
            var quiz = await _context.Quizzes.FirstOrDefaultAsync(x => x.Id == id); 
            if(quiz != null)
            {
                _context.Quizzes.Remove(quiz);
                await _context.SaveChangesAsync(); 
            }

            return RedirectToAction("List", new { botId = quiz.BotId }); 
        }

        #region Steps

        public IActionResult CreateStep(int quizId)
        {
            return View(new QuizStepViewModel { QuizId = quizId });
        }

        [HttpPost]
        public async Task<IActionResult> CreateStep(QuizStepViewModel model)
        {
            if(ModelState.IsValid)
            {
                await _context.QuizSteps.AddAsync(new QuizStep
                {
                    Name = model.Name, 
                    Text = model.Text,
                    QuizId = model.QuizId,
                    StepNumber = model.StepNumber
                });

                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", new { id = model.QuizId }); 
            }

            return View(model); 
        }

        public async Task<IActionResult> EditStep(int id)
        {
            var step = await _context.QuizSteps.FirstOrDefaultAsync(x => x.Id == id);
            if(step != null)
            {
                return View(new QuizStepViewModel
                {
                    Id = step.Id,
                    QuizId = step.QuizId,
                    Name = step.Name,
                    Text = step.Text,
                    StepNumber = step.StepNumber
                }); 
            }
            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> EditStep(QuizStepViewModel model)
        {
            if(ModelState.IsValid)
            {
                var step = await _context.QuizSteps.FirstOrDefaultAsync(x => x.Id == model.Id); 
                if(step != null)
                {
                    step.QuizId = model.QuizId;
                    step.Name = model.Name;
                    step.Text = model.Text;
                    step.StepNumber = model.StepNumber;
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Edit", new { id = model.QuizId }); 
                }
            }
            return View(model); 
        }

        public async Task<IActionResult> DeleteStep(int id)
        {
            var step = await _context.QuizSteps.FirstOrDefaultAsync(x => x.Id == id); 
            if(step != null)
            {
                _context.QuizSteps.Remove(step);
                await _context.SaveChangesAsync(); 
            }
            return RedirectToAction("Edit", new { id = step.QuizId }); 
        }

        #endregion
    }
}

BotConstructor/Views/Bot/Dashboard.cshtml
@model BotConstructor.Web.Models.Bot.DashboardViewModel
@{
    ViewData["Title"] = "Dashboard";
}

<h3>Dashboard - @Model.BotName</h3>
<hr />

<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link" asp-action="Edit" asp-controller="Bot" asp-route-id="@Model.BotId">General</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="List" asp-controller="Message" asp-route-botId="@Model.BotId">Messages</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" asp-action="List" asp-controller="Quiz" asp-route-botId="@Model.BotId">Quizes</a>
    </li>
</ul>

BotConstructor/Views/Bot/Edit.cshtml
@model BotConstructor.Web.Models.Bot.BotEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h3>Edit - @Model.Name</h3>
<hr />
<form asp-action="Edit" asp-controller="Bot" method="post" class="mt-3">
    <input asp-for="Id" type="hidden" />
    <div class="row">
        <div class="form-group col-6 row">
            <label class="col-form-label col-form-label-sm col-2">Name</label>
            <div class="col-10">
                <input asp-for="Name" class="form-control form-control-sm" type="text" />
            </div>
        </div>

        <div class="form-group col-6 row">
            <label class="col-form-label col-form-label-sm col-2">Token</label>
            <div class="col-10">
                <input asp-for="Token" class="form-control form-control-sm" type="text" />
            </div>
        </div>

        <div class="col-12">
            <button class="btn btn-success">Save</button>
            <a asp-action="List" asp-controller="Bot" class="btn btn-link">Cancel</a>
        </div>
    </div>
</form>

<h5 class="d-flex justify-content-between mt-3">
    Bot saved Text Messages:
    <a asp-action="Create" asp-controller="Message" asp-route-botId="@Model.Id" class="btn btn-success btn-sm">+</a>
</h5>

<hr />

@foreach(var message in Model.Messages)
{
    <div class="list-group">
        <a asp-action="Edit" asp-controller="Message" asp-route-id="@message.Id" class="list-group-item list-group-item-action">@message.InputMessage</a>
    </div>
}

BotConstructor/Views/Bot/List.cshtml
@model List<BotConstructor.Web.Models.Bot.BotListViewModel>
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

@await Html.PartialAsync("NewBotPartial", new BotConstructor.Web.Models.Bot.BotViewModel())

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var bot in Model)
        {
            <tr>
                <td>@bot.Id</td>
                <td><a asp-action="Dashboard" asp-controller="Bot" asp-route-id="@bot.Id">@bot.Name</a></td>
                <td class="text-right">
                    @if(bot.IsWorking)
                    {
                        <a asp-action="StopBot" asp-controller="Bot" asp-route-id="@bot.Id" class="btn btn-danger btn-sm">Stop</a>
                    }
                    else
                    {
                        <a asp-action="StartBot" asp-controller="Bot" asp-route-id="@bot.Id" class="btn btn-success btn-sm">Start</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

BotConstructor/Views/Bot/NewBotPartial.cshtml
@model BotConstructor.Web.Models.Bot.BotViewModel

<form asp-action="AddBot" asp-controller="Bot" method="post">
    <div class="row">
        <div asp-validation-summary="All" class="text-danger col-12"></div>
        <div class="form-group col-5 row">
            <label class="col-form-label col-form-label-sm col-4">Token</label>
            <div class="col-8">
                <input asp-for="Token" type="text" class="form-control form-control-sm" />
            </div>
        </div>
        <div class="form-group col-5 row">
            <label class="col-form-label col-form-label-sm col-4">Name</label>
            <div class="col-8">
                <input asp-for="Name" type="text" class="form-control form-control-sm" />
            </div>
        </div>
        <div class="col-2">
            <button type="submit" class="btn btn-success btn-sm">Create</button>
        </div>
    </div>
</form>